title: Portfolio de Vincent REHM
description: Contactez-moi pour vos projets numériques

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
